import { fileURLToPath, URL } from 'node:url'
import vue from '@vitejs/plugin-vue'
import UnoCSS from 'unocss/vite'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { VantResolver } from '@vant/auto-import-resolver'
import mobileForever from 'postcss-mobile-forever'
import { viteVConsole } from 'vite-plugin-vconsole'

// Vite+ reads `lint`/`fmt` statically from the default export, so the config
// must be a plain object (not a `({ mode }) => ...` function). Derive the mode
// from argv at load time to keep per-mode build behavior (staging keeps console
// + sourcemaps, production strips them).
const argv = process.argv
const modeFlagIndex = argv.indexOf('--mode')
// `argv[modeFlagIndex + 1]` is undefined when `--mode` is passed without a
// value, so fall back to the command instead of an undefined mode.
const modeArg = modeFlagIndex !== -1 ? argv[modeFlagIndex + 1] : undefined
const isBuildCommand = argv.includes('build')
const mode = modeArg ?? (isBuildCommand ? 'production' : 'development')
const isProd = mode === 'production'

// `defineConfig` is intentionally omitted: its overload resolution against the
// large `lint` block crashes vue-tsc/TS 6. Vite+ reads the plain default export.
export default {
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'vue'],
    categories: { correctness: 'warn' },
    env: { builtin: true },
    ignorePatterns: ['**/dist/**', '**/dist-ssr/**', '**/coverage/**'],
    rules: {
      'vue/no-arrow-functions-in-watch': 'error',
      'vue/no-deprecated-data-object-declaration': 'error',
      'vue/no-deprecated-delete-set': 'error',
      'vue/no-deprecated-destroyed-lifecycle': 'error',
      'vue/no-deprecated-events-api': 'error',
      'vue/no-deprecated-model-definition': 'error',
      'vue/no-deprecated-vue-config-keycodes': 'error',
      'vue/no-export-in-script-setup': 'error',
      'vue/no-lifecycle-after-await': 'error',
      'vue/prefer-import-from-vue': 'error',
      'vue/return-in-computed-property': 'error',
      'vue/valid-define-emits': 'error',
      'vue/valid-define-props': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'no-unused-vars': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
  },
  fmt: {
    semi: false,
    singleQuote: true,
    arrowParens: 'avoid',
    printWidth: 80,
    // Generated by unplugin-auto-import / unplugin-vue-components on every build.
    ignorePatterns: ['auto-imports.d.ts', 'components.d.ts'],
  },
  plugins: [
    vue(),
    UnoCSS(),
    AutoImport({
      imports: ['vue', 'vue-router', 'pinia', '@vueuse/core'],
      resolvers: [VantResolver()],
      dts: 'auto-imports.d.ts',
    }),
    Components({
      resolvers: [VantResolver()],
      dts: 'components.d.ts',
    }),
    viteVConsole({
      entry: [fileURLToPath(new URL('./src/main.ts', import.meta.url))],
      enabled: !isProd,
      config: { maxLogNumber: 1000, theme: 'dark' },
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    host: true,
    port: 9527,
    proxy: {
      '/api': {
        target: 'http://api.example.com',
        changeOrigin: true,
        rewrite: (path: string) => path.replace(/^\/api/, ''),
      },
    },
  },
  css: {
    postcss: {
      plugins: [
        mobileForever({
          appSelector: '#app',
          viewportWidth: 375,
          maxDisplayWidth: 600,
          unitPrecision: 6,
          propList: ['*'],
          selectorBlackList: ['ignore-'],
          // oxlint-disable-next-line typescript/no-explicit-any
        }) as any,
      ],
    },
  },
  build: {
    sourcemap: !isProd,
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: isProd,
        drop_debugger: isProd,
      },
    },
    rollupOptions: {
      output: {
        manualChunks(id: string) {
          if (/node_modules\/(vue|vue-router|pinia)\//.test(id))
            return 'vue-vendor'
          if (/node_modules\/vant\//.test(id)) return 'vant-vendor'
        },
      },
    },
  },
  test: {
    environment: 'jsdom',
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.{ts,vue}'],
      exclude: ['src/**/*.d.ts', 'src/main.ts'],
    },
  },
}
